import React, { useState } from 'react';
import { useStore } from '../store/useStore';
import { format } from 'date-fns';
import { Printer, FileBox, Download } from 'lucide-react';

export default function Reports() {
  const { settings } = useStore();
  const [reportType, setReportType] = useState('monthly');
  const [dateRange, setDateRange] = useState('');

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="flex flex-col gap-6 animate-fade-in">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 no-print">
        <h1 className="page-title">Reports</h1>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 no-print">
        
        {/* Generate Report */}
        <div className="card">
          <h3 className="card-title mb-6">Generate Report</h3>
          <div className="flex flex-col gap-4">
            <div>
              <label className="block text-[12px] font-medium text-text-secondary mb-1">Report Type</label>
              <select 
                className="w-full px-3 py-2 bg-page-light dark:bg-page-dark border border-border-light dark:border-border-dark rounded-[8px] text-[14px] text-text-primary dark:text-white focus:outline-none focus:border-primary"
                value={reportType}
                onChange={(e) => setReportType(e.target.value)}
              >
                <option value="monthly">Monthly Summary</option>
                <option value="annual">Annual Report</option>
                <option value="event">Event Report</option>
                <option value="audit">Audit Report</option>
              </select>
            </div>
            <div>
              <label className="block text-[12px] font-medium text-text-secondary mb-1">Date Range</label>
              <input 
                type="month" 
                className="w-full px-3 py-2 bg-page-light dark:bg-page-dark border border-border-light dark:border-border-dark rounded-[8px] text-[14px] text-text-primary dark:text-white focus:outline-none focus:border-primary"
                value={dateRange}
                onChange={(e) => setDateRange(e.target.value)}
              />
            </div>
            <div className="mt-4">
              <button className="btn-primary w-full" onClick={handlePrint}>
                <Printer size={16} /> Generate PDF
              </button>
            </div>
          </div>
        </div>

        {/* Saved Reports */}
        <div className="card">
          <h3 className="card-title mb-6">Saved Reports</h3>
          <div className="flex flex-col items-center justify-center py-12 text-center gap-3">
            <FileBox size={48} className="text-text-tertiary opacity-50" />
            <div className="text-text-secondary text-[14px]">No saved reports yet.</div>
          </div>
        </div>

      </div>

      {/* Print View Only */}
      <div className="hidden print-only py-8">
        <div className="text-center mb-8 border-b pb-4">
          <h1 className="text-2xl font-bold">{settings.clubName}</h1>
          <h2 className="text-xl text-gray-600 mt-2 capitalize">{reportType} Report</h2>
          <p className="text-gray-500 mt-1">Generated on {format(new Date(), 'MMMM dd, yyyy')}</p>
        </div>
        <div className="mt-8">
          <p className="text-gray-600 italic">This document is auto-generated by {settings.clubName}.</p>
          <div className="mt-8 border p-6 rounded text-center">
            [ Report contents would be fully rendered here based on the selected type ]
          </div>
        </div>
      </div>

    </div>
  );
}
